<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry\Event;

use UnexpectedValueException;

/**
 * Protobuf type <code>PhpSentryProtobuf.MySentry.Event.Severity</code>
 */
class Severity
{
    /**
     *debug severity level
     *
     * Generated from protobuf enum <code>severity_debug = 0;</code>
     */
    const severity_debug = 0;
    /**
     *info severity level
     *
     * Generated from protobuf enum <code>severity_info = 1;</code>
     */
    const severity_info = 1;
    /**
     *warning severity level
     *
     * Generated from protobuf enum <code>severity_warning = 2;</code>
     */
    const severity_warning = 2;
    /**
     *error severity level
     *
     * Generated from protobuf enum <code>severity_error = 3;</code>
     */
    const severity_error = 3;
    /**
     *fatal severity level
     *
     * Generated from protobuf enum <code>severity_fatal = 4;</code>
     */
    const severity_fatal = 4;

    private static $valueToName = [
        self::severity_debug => 'severity_debug',
        self::severity_info => 'severity_info',
        self::severity_warning => 'severity_warning',
        self::severity_error => 'severity_error',
        self::severity_fatal => 'severity_fatal',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Severity::class, \PhpSentryProtobuf\MySentry\Event_Severity::class);

