<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpSentryProtobuf.MySentry.Breadcrumb</code>
 */
class Breadcrumb extends \Google\Protobuf\Internal\Message
{
    /**
     *The category of the breadcrumb
     *
     * Generated from protobuf field <code>string category = 1;</code>
     */
    protected $category = '';
    /**
     *The type of breadcrumb
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Type type = 2;</code>
     */
    protected $type = 0;
    /**
     *The message of the breadcrumb
     *
     * Generated from protobuf field <code>string message = 3;</code>
     */
    protected $message = '';
    /**
     *The level of the breadcrumb
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Level level = 4;</code>
     */
    protected $level = 0;
    /**
     *The meta data of the breadcrumb
     *
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     */
    private $metadata;
    /**
     *The timestamp of the breadcrumb
     *
     * Generated from protobuf field <code>float timestamp = 6;</code>
     */
    protected $timestamp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $category
     *          The category of the breadcrumb
     *     @type int $type
     *          The type of breadcrumb
     *     @type string $message
     *          The message of the breadcrumb
     *     @type int $level
     *          The level of the breadcrumb
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     *          The meta data of the breadcrumb
     *     @type float $timestamp
     *          The timestamp of the breadcrumb
     * }
     */
    public function __construct($data = NULL) {
        \PhpSentryProtobuf\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     *The category of the breadcrumb
     *
     * Generated from protobuf field <code>string category = 1;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     *The category of the breadcrumb
     *
     * Generated from protobuf field <code>string category = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     *The type of breadcrumb
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Type type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *The type of breadcrumb
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Type type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \PhpSentryProtobuf\MySentry\Breadcrumb\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     *The message of the breadcrumb
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     *The message of the breadcrumb
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     *The level of the breadcrumb
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Level level = 4;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     *The level of the breadcrumb
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Level level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkEnum($var, \PhpSentryProtobuf\MySentry\Breadcrumb\Level::class);
        $this->level = $var;

        return $this;
    }

    /**
     *The meta data of the breadcrumb
     *
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     *The meta data of the breadcrumb
     *
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

    /**
     *The timestamp of the breadcrumb
     *
     * Generated from protobuf field <code>float timestamp = 6;</code>
     * @return float
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     *The timestamp of the breadcrumb
     *
     * Generated from protobuf field <code>float timestamp = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkFloat($var);
        $this->timestamp = $var;

        return $this;
    }

}

