<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpSentryProtobuf.MySentry.Breadcrumb</code>
 */
class Breadcrumb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string category = 1;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Type type = 2;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string message = 3;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Level level = 4;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>float timestamp = 5;</code>
     */
    protected $timestamp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $category
     *     @type int $type
     *     @type string $message
     *     @type int $level
     *     @type float $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \PhpSentryProtobuf\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string category = 1;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Type type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Type type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \PhpSentryProtobuf\MySentry\Breadcrumb\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Level level = 4;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Breadcrumb.Level level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkEnum($var, \PhpSentryProtobuf\MySentry\Breadcrumb\Level::class);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float timestamp = 5;</code>
     * @return float
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>float timestamp = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkFloat($var);
        $this->timestamp = $var;

        return $this;
    }

}

