<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpSentryProtobuf.MySentry.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     */
    protected $eventId = '';
    /**
     * Generated from protobuf field <code>float timestamp = 2;</code>
     */
    protected $timestamp = 0.0;
    /**
     * Generated from protobuf field <code>float startTimestamp = 3;</code>
     */
    protected $startTimestamp = 0.0;
    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Event.Severity level = 4;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>string release = 5;</code>
     */
    protected $release = '';
    /**
     * Generated from protobuf field <code>string message = 6;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>string messageFormatted = 7;</code>
     */
    protected $messageFormatted = '';
    /**
     * Generated from protobuf field <code>repeated string messageParams = 8;</code>
     */
    private $messageParams;
    /**
     * Generated from protobuf field <code>string environment = 9;</code>
     */
    protected $environment = '';
    /**
     * Generated from protobuf field <code>repeated string fingerprint = 10;</code>
     */
    private $fingerprint;
    /**
     * Generated from protobuf field <code>repeated .PhpSentryProtobuf.MySentry.Exception exceptions = 11;</code>
     */
    private $exceptions;
    /**
     * Generated from protobuf field <code>string sdkIdentifier = 12;</code>
     */
    protected $sdkIdentifier = '';
    /**
     * Generated from protobuf field <code>string sdkVersion = 13;</code>
     */
    protected $sdkVersion = '';
    /**
     * Generated from protobuf field <code>string type = 14;</code>
     */
    protected $type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $eventId
     *     @type float $timestamp
     *     @type float $startTimestamp
     *     @type int $level
     *     @type string $release
     *     @type string $message
     *     @type string $messageFormatted
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $messageParams
     *     @type string $environment
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $fingerprint
     *     @type array<\PhpSentryProtobuf\MySentry\Exception>|\Google\Protobuf\Internal\RepeatedField $exceptions
     *     @type string $sdkIdentifier
     *     @type string $sdkVersion
     *     @type string $type
     * }
     */
    public function __construct($data = NULL) {
        \PhpSentryProtobuf\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     * @return string
     */
    public function getEventId()
    {
        return $this->eventId;
    }

    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float timestamp = 2;</code>
     * @return float
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>float timestamp = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkFloat($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float startTimestamp = 3;</code>
     * @return float
     */
    public function getStartTimestamp()
    {
        return $this->startTimestamp;
    }

    /**
     * Generated from protobuf field <code>float startTimestamp = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkFloat($var);
        $this->startTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Event.Severity level = 4;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Event.Severity level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkEnum($var, \PhpSentryProtobuf\MySentry\Event\Severity::class);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string release = 5;</code>
     * @return string
     */
    public function getRelease()
    {
        return $this->release;
    }

    /**
     * Generated from protobuf field <code>string release = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRelease($var)
    {
        GPBUtil::checkString($var, True);
        $this->release = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 6;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string messageFormatted = 7;</code>
     * @return string
     */
    public function getMessageFormatted()
    {
        return $this->messageFormatted;
    }

    /**
     * Generated from protobuf field <code>string messageFormatted = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageFormatted($var)
    {
        GPBUtil::checkString($var, True);
        $this->messageFormatted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string messageParams = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMessageParams()
    {
        return $this->messageParams;
    }

    /**
     * Generated from protobuf field <code>repeated string messageParams = 8;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMessageParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->messageParams = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string environment = 9;</code>
     * @return string
     */
    public function getEnvironment()
    {
        return $this->environment;
    }

    /**
     * Generated from protobuf field <code>string environment = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setEnvironment($var)
    {
        GPBUtil::checkString($var, True);
        $this->environment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string fingerprint = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFingerprint()
    {
        return $this->fingerprint;
    }

    /**
     * Generated from protobuf field <code>repeated string fingerprint = 10;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFingerprint($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->fingerprint = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PhpSentryProtobuf.MySentry.Exception exceptions = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExceptions()
    {
        return $this->exceptions;
    }

    /**
     * Generated from protobuf field <code>repeated .PhpSentryProtobuf.MySentry.Exception exceptions = 11;</code>
     * @param array<\PhpSentryProtobuf\MySentry\Exception>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExceptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PhpSentryProtobuf\MySentry\Exception::class);
        $this->exceptions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sdkIdentifier = 12;</code>
     * @return string
     */
    public function getSdkIdentifier()
    {
        return $this->sdkIdentifier;
    }

    /**
     * Generated from protobuf field <code>string sdkIdentifier = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->sdkIdentifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sdkVersion = 13;</code>
     * @return string
     */
    public function getSdkVersion()
    {
        return $this->sdkVersion;
    }

    /**
     * Generated from protobuf field <code>string sdkVersion = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setSdkVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->sdkVersion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 14;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

}

