<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpSentryProtobuf.MySentry.Exception</code>
 */
class Exception extends \Google\Protobuf\Internal\Message
{
    /**
     *The type of exception, e.g. RuntimeException
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     *The value of the exception
     *
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';
    /**
     *The stack trace of exception
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Stacktrace stacktrace = 3;</code>
     */
    protected $stacktrace = null;
    /**
     *The mechanism that created this exception
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.ExceptionMechanism mechanism = 4;</code>
     */
    protected $mechanism = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *          The type of exception, e.g. RuntimeException
     *     @type string $value
     *          The value of the exception
     *     @type \PhpSentryProtobuf\MySentry\Stacktrace $stacktrace
     *          The stack trace of exception
     *     @type \PhpSentryProtobuf\MySentry\ExceptionMechanism $mechanism
     *          The mechanism that created this exception
     * }
     */
    public function __construct($data = NULL) {
        \PhpSentryProtobuf\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     *The type of exception, e.g. RuntimeException
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *The type of exception, e.g. RuntimeException
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     *The value of the exception
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     *The value of the exception
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     *The stack trace of exception
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Stacktrace stacktrace = 3;</code>
     * @return \PhpSentryProtobuf\MySentry\Stacktrace|null
     */
    public function getStacktrace()
    {
        return $this->stacktrace;
    }

    public function hasStacktrace()
    {
        return isset($this->stacktrace);
    }

    public function clearStacktrace()
    {
        unset($this->stacktrace);
    }

    /**
     *The stack trace of exception
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.Stacktrace stacktrace = 3;</code>
     * @param \PhpSentryProtobuf\MySentry\Stacktrace $var
     * @return $this
     */
    public function setStacktrace($var)
    {
        GPBUtil::checkMessage($var, \PhpSentryProtobuf\MySentry\Stacktrace::class);
        $this->stacktrace = $var;

        return $this;
    }

    /**
     *The mechanism that created this exception
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.ExceptionMechanism mechanism = 4;</code>
     * @return \PhpSentryProtobuf\MySentry\ExceptionMechanism|null
     */
    public function getMechanism()
    {
        return $this->mechanism;
    }

    public function hasMechanism()
    {
        return isset($this->mechanism);
    }

    public function clearMechanism()
    {
        unset($this->mechanism);
    }

    /**
     *The mechanism that created this exception
     *
     * Generated from protobuf field <code>.PhpSentryProtobuf.MySentry.ExceptionMechanism mechanism = 4;</code>
     * @param \PhpSentryProtobuf\MySentry\ExceptionMechanism $var
     * @return $this
     */
    public function setMechanism($var)
    {
        GPBUtil::checkMessage($var, \PhpSentryProtobuf\MySentry\ExceptionMechanism::class);
        $this->mechanism = $var;

        return $this;
    }

}

