<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpSentryProtobuf.MySentry.Frame</code>
 */
class Frame extends \Google\Protobuf\Internal\Message
{
    /**
     *The name of the function being called
     *
     * Generated from protobuf field <code>string functionName = 1;</code>
     */
    protected $functionName = '';
    /**
     *The original function name, if the function name is shortened or demangled
     *
     * Generated from protobuf field <code>string rawFunctionName = 2;</code>
     */
    protected $rawFunctionName = '';
    /**
     *The file where the frame originated
     *
     * Generated from protobuf field <code>string file = 3;</code>
     */
    protected $file = '';
    /**
     *The absolute path to the source file
     *
     * Generated from protobuf field <code>string absoluteFilePath = 4;</code>
     */
    protected $absoluteFilePath = '';
    /**
     *The line at which the frame originated
     *
     * Generated from protobuf field <code>int32 line = 5;</code>
     */
    protected $line = 0;
    /**
     *A list of source code lines before the one where the frame originated
     *
     * Generated from protobuf field <code>repeated string preContext = 6;</code>
     */
    private $preContext;
    /**
     *The source code written at the line number of the file that originated this frame
     *
     * Generated from protobuf field <code>string contextLine = 7;</code>
     */
    protected $contextLine = '';
    /**
     *A list of source code lines after the one where the frame originated
     *
     * Generated from protobuf field <code>repeated string postContext = 8;</code>
     */
    private $postContext;
    /**
     *Flag telling whether the frame is related to the execution of the relevant code in this stacktrace
     *
     * Generated from protobuf field <code>bool inApp = 9;</code>
     */
    protected $inApp = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $functionName
     *          The name of the function being called
     *     @type string $rawFunctionName
     *          The original function name, if the function name is shortened or demangled
     *     @type string $file
     *          The file where the frame originated
     *     @type string $absoluteFilePath
     *          The absolute path to the source file
     *     @type int $line
     *          The line at which the frame originated
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $preContext
     *          A list of source code lines before the one where the frame originated
     *     @type string $contextLine
     *          The source code written at the line number of the file that originated this frame
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $postContext
     *          A list of source code lines after the one where the frame originated
     *     @type bool $inApp
     *          Flag telling whether the frame is related to the execution of the relevant code in this stacktrace
     * }
     */
    public function __construct($data = NULL) {
        \PhpSentryProtobuf\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     *The name of the function being called
     *
     * Generated from protobuf field <code>string functionName = 1;</code>
     * @return string
     */
    public function getFunctionName()
    {
        return $this->functionName;
    }

    /**
     *The name of the function being called
     *
     * Generated from protobuf field <code>string functionName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFunctionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->functionName = $var;

        return $this;
    }

    /**
     *The original function name, if the function name is shortened or demangled
     *
     * Generated from protobuf field <code>string rawFunctionName = 2;</code>
     * @return string
     */
    public function getRawFunctionName()
    {
        return $this->rawFunctionName;
    }

    /**
     *The original function name, if the function name is shortened or demangled
     *
     * Generated from protobuf field <code>string rawFunctionName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRawFunctionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->rawFunctionName = $var;

        return $this;
    }

    /**
     *The file where the frame originated
     *
     * Generated from protobuf field <code>string file = 3;</code>
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     *The file where the frame originated
     *
     * Generated from protobuf field <code>string file = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->file = $var;

        return $this;
    }

    /**
     *The absolute path to the source file
     *
     * Generated from protobuf field <code>string absoluteFilePath = 4;</code>
     * @return string
     */
    public function getAbsoluteFilePath()
    {
        return $this->absoluteFilePath;
    }

    /**
     *The absolute path to the source file
     *
     * Generated from protobuf field <code>string absoluteFilePath = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAbsoluteFilePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->absoluteFilePath = $var;

        return $this;
    }

    /**
     *The line at which the frame originated
     *
     * Generated from protobuf field <code>int32 line = 5;</code>
     * @return int
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     *The line at which the frame originated
     *
     * Generated from protobuf field <code>int32 line = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLine($var)
    {
        GPBUtil::checkInt32($var);
        $this->line = $var;

        return $this;
    }

    /**
     *A list of source code lines before the one where the frame originated
     *
     * Generated from protobuf field <code>repeated string preContext = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPreContext()
    {
        return $this->preContext;
    }

    /**
     *A list of source code lines before the one where the frame originated
     *
     * Generated from protobuf field <code>repeated string preContext = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPreContext($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->preContext = $arr;

        return $this;
    }

    /**
     *The source code written at the line number of the file that originated this frame
     *
     * Generated from protobuf field <code>string contextLine = 7;</code>
     * @return string
     */
    public function getContextLine()
    {
        return $this->contextLine;
    }

    /**
     *The source code written at the line number of the file that originated this frame
     *
     * Generated from protobuf field <code>string contextLine = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setContextLine($var)
    {
        GPBUtil::checkString($var, True);
        $this->contextLine = $var;

        return $this;
    }

    /**
     *A list of source code lines after the one where the frame originated
     *
     * Generated from protobuf field <code>repeated string postContext = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPostContext()
    {
        return $this->postContext;
    }

    /**
     *A list of source code lines after the one where the frame originated
     *
     * Generated from protobuf field <code>repeated string postContext = 8;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPostContext($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->postContext = $arr;

        return $this;
    }

    /**
     *Flag telling whether the frame is related to the execution of the relevant code in this stacktrace
     *
     * Generated from protobuf field <code>bool inApp = 9;</code>
     * @return bool
     */
    public function getInApp()
    {
        return $this->inApp;
    }

    /**
     *Flag telling whether the frame is related to the execution of the relevant code in this stacktrace
     *
     * Generated from protobuf field <code>bool inApp = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setInApp($var)
    {
        GPBUtil::checkBool($var);
        $this->inApp = $var;

        return $this;
    }

}

