<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpSentryProtobuf.MySentry.OsContext</code>
 */
class OsContext extends \Google\Protobuf\Internal\Message
{
    /**
     *The name of the operating system
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *The version of the operating system
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';
    /**
     *The internal build revision of the operating system
     *
     * Generated from protobuf field <code>string build = 3;</code>
     */
    protected $build = '';
    /**
     *An independent kernel version string
     *
     * Generated from protobuf field <code>string kernelVersion = 4;</code>
     */
    protected $kernelVersion = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          The name of the operating system
     *     @type string $version
     *          The version of the operating system
     *     @type string $build
     *          The internal build revision of the operating system
     *     @type string $kernelVersion
     *          An independent kernel version string
     * }
     */
    public function __construct($data = NULL) {
        \PhpSentryProtobuf\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     *The name of the operating system
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *The name of the operating system
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *The version of the operating system
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *The version of the operating system
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     *The internal build revision of the operating system
     *
     * Generated from protobuf field <code>string build = 3;</code>
     * @return string
     */
    public function getBuild()
    {
        return $this->build;
    }

    /**
     *The internal build revision of the operating system
     *
     * Generated from protobuf field <code>string build = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBuild($var)
    {
        GPBUtil::checkString($var, True);
        $this->build = $var;

        return $this;
    }

    /**
     *An independent kernel version string
     *
     * Generated from protobuf field <code>string kernelVersion = 4;</code>
     * @return string
     */
    public function getKernelVersion()
    {
        return $this->kernelVersion;
    }

    /**
     *An independent kernel version string
     *
     * Generated from protobuf field <code>string kernelVersion = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setKernelVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->kernelVersion = $var;

        return $this;
    }

}

