<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpSentryProtobuf.MySentry.Span</code>
 */
class Span extends \Google\Protobuf\Internal\Message
{
    /**
     *Span ID
     *
     * Generated from protobuf field <code>string spanId = 1;</code>
     */
    protected $spanId = '';
    /**
     *Trace ID
     *
     * Generated from protobuf field <code>string traceId = 2;</code>
     */
    protected $traceId = '';
    /**
     *Description of the span
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     *Operation of the span
     *
     * Generated from protobuf field <code>string op = 4;</code>
     */
    protected $op = '';
    /**
     *Completion status of the span
     *
     * Generated from protobuf field <code>string status = 5;</code>
     */
    protected $status = '';
    /**
     *ID of the parent span
     *
     * Generated from protobuf field <code>string parentSpanId = 6;</code>
     */
    protected $parentSpanId = '';
    /**
     *Has the sample decision been made?
     *
     * Generated from protobuf field <code>bool sampled = 7;</code>
     */
    protected $sampled = false;
    /**
     *A List of tags associated to this span
     *
     * Generated from protobuf field <code>map<string, string> tags = 8;</code>
     */
    private $tags;
    /**
     *An arbitrary mapping of additional metadata
     *
     * Generated from protobuf field <code>map<string, string> data = 9;</code>
     */
    private $data;
    /**
     *Timestamp in seconds (epoch time) indicating when the span started
     *
     * Generated from protobuf field <code>float startTimestamp = 10;</code>
     */
    protected $startTimestamp = 0.0;
    /**
     *Timestamp in seconds (epoch time) indicating when the span ended
     *
     * Generated from protobuf field <code>float endTimestamp = 11;</code>
     */
    protected $endTimestamp = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $spanId
     *          Span ID
     *     @type string $traceId
     *          Trace ID
     *     @type string $description
     *          Description of the span
     *     @type string $op
     *          Operation of the span
     *     @type string $status
     *          Completion status of the span
     *     @type string $parentSpanId
     *          ID of the parent span
     *     @type bool $sampled
     *          Has the sample decision been made?
     *     @type array|\Google\Protobuf\Internal\MapField $tags
     *          A List of tags associated to this span
     *     @type array|\Google\Protobuf\Internal\MapField $data
     *          An arbitrary mapping of additional metadata
     *     @type float $startTimestamp
     *          Timestamp in seconds (epoch time) indicating when the span started
     *     @type float $endTimestamp
     *          Timestamp in seconds (epoch time) indicating when the span ended
     * }
     */
    public function __construct($data = NULL) {
        \PhpSentryProtobuf\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     *Span ID
     *
     * Generated from protobuf field <code>string spanId = 1;</code>
     * @return string
     */
    public function getSpanId()
    {
        return $this->spanId;
    }

    /**
     *Span ID
     *
     * Generated from protobuf field <code>string spanId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpanId($var)
    {
        GPBUtil::checkString($var, True);
        $this->spanId = $var;

        return $this;
    }

    /**
     *Trace ID
     *
     * Generated from protobuf field <code>string traceId = 2;</code>
     * @return string
     */
    public function getTraceId()
    {
        return $this->traceId;
    }

    /**
     *Trace ID
     *
     * Generated from protobuf field <code>string traceId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTraceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->traceId = $var;

        return $this;
    }

    /**
     *Description of the span
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     *Description of the span
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     *Operation of the span
     *
     * Generated from protobuf field <code>string op = 4;</code>
     * @return string
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     *Operation of the span
     *
     * Generated from protobuf field <code>string op = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkString($var, True);
        $this->op = $var;

        return $this;
    }

    /**
     *Completion status of the span
     *
     * Generated from protobuf field <code>string status = 5;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *Completion status of the span
     *
     * Generated from protobuf field <code>string status = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     *ID of the parent span
     *
     * Generated from protobuf field <code>string parentSpanId = 6;</code>
     * @return string
     */
    public function getParentSpanId()
    {
        return $this->parentSpanId;
    }

    /**
     *ID of the parent span
     *
     * Generated from protobuf field <code>string parentSpanId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setParentSpanId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parentSpanId = $var;

        return $this;
    }

    /**
     *Has the sample decision been made?
     *
     * Generated from protobuf field <code>bool sampled = 7;</code>
     * @return bool
     */
    public function getSampled()
    {
        return $this->sampled;
    }

    /**
     *Has the sample decision been made?
     *
     * Generated from protobuf field <code>bool sampled = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setSampled($var)
    {
        GPBUtil::checkBool($var);
        $this->sampled = $var;

        return $this;
    }

    /**
     *A List of tags associated to this span
     *
     * Generated from protobuf field <code>map<string, string> tags = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     *A List of tags associated to this span
     *
     * Generated from protobuf field <code>map<string, string> tags = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     *An arbitrary mapping of additional metadata
     *
     * Generated from protobuf field <code>map<string, string> data = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *An arbitrary mapping of additional metadata
     *
     * Generated from protobuf field <code>map<string, string> data = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->data = $arr;

        return $this;
    }

    /**
     *Timestamp in seconds (epoch time) indicating when the span started
     *
     * Generated from protobuf field <code>float startTimestamp = 10;</code>
     * @return float
     */
    public function getStartTimestamp()
    {
        return $this->startTimestamp;
    }

    /**
     *Timestamp in seconds (epoch time) indicating when the span started
     *
     * Generated from protobuf field <code>float startTimestamp = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkFloat($var);
        $this->startTimestamp = $var;

        return $this;
    }

    /**
     *Timestamp in seconds (epoch time) indicating when the span ended
     *
     * Generated from protobuf field <code>float endTimestamp = 11;</code>
     * @return float
     */
    public function getEndTimestamp()
    {
        return $this->endTimestamp;
    }

    /**
     *Timestamp in seconds (epoch time) indicating when the span ended
     *
     * Generated from protobuf field <code>float endTimestamp = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setEndTimestamp($var)
    {
        GPBUtil::checkFloat($var);
        $this->endTimestamp = $var;

        return $this;
    }

}

