<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpSentryProtobuf.MySentry.Stacktrace</code>
 */
class Stacktrace extends \Google\Protobuf\Internal\Message
{
    /**
     *The frames that compose the stacktrace
     *
     * Generated from protobuf field <code>repeated .PhpSentryProtobuf.MySentry.Frame frames = 1;</code>
     */
    private $frames;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\PhpSentryProtobuf\MySentry\Frame>|\Google\Protobuf\Internal\RepeatedField $frames
     *          The frames that compose the stacktrace
     * }
     */
    public function __construct($data = NULL) {
        \PhpSentryProtobuf\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     *The frames that compose the stacktrace
     *
     * Generated from protobuf field <code>repeated .PhpSentryProtobuf.MySentry.Frame frames = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFrames()
    {
        return $this->frames;
    }

    /**
     *The frames that compose the stacktrace
     *
     * Generated from protobuf field <code>repeated .PhpSentryProtobuf.MySentry.Frame frames = 1;</code>
     * @param array<\PhpSentryProtobuf\MySentry\Frame>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFrames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PhpSentryProtobuf\MySentry\Frame::class);
        $this->frames = $arr;

        return $this;
    }

}

