<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Event.proto

namespace PhpSentryProtobuf\MySentry\Breadcrumb;

use UnexpectedValueException;

/**
 * Protobuf type <code>PhpSentryProtobuf.MySentry.Breadcrumb.Level</code>
 */
class Level
{
    /**
     *debug level for a breadcrumb
     *
     * Generated from protobuf enum <code>level_debug = 0;</code>
     */
    const level_debug = 0;
    /**
     *info level for a breadcrumb
     *
     * Generated from protobuf enum <code>level_info = 1;</code>
     */
    const level_info = 1;
    /**
     *warning level for a breadcrumb
     *
     * Generated from protobuf enum <code>level_warning = 2;</code>
     */
    const level_warning = 2;
    /**
     *error level for a breadcrumb
     *
     * Generated from protobuf enum <code>level_error = 3;</code>
     */
    const level_error = 3;
    /**
     *fatal level for a breadcrumb
     *
     * Generated from protobuf enum <code>level_fatal = 4;</code>
     */
    const level_fatal = 4;

    private static $valueToName = [
        self::level_debug => 'level_debug',
        self::level_info => 'level_info',
        self::level_warning => 'level_warning',
        self::level_error => 'level_error',
        self::level_fatal => 'level_fatal',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Level::class, \PhpSentryProtobuf\MySentry\Breadcrumb_Level::class);

